version: "3.1"

services:
  apache:
    build: .
    volumes:
      - ./app/php:/var/www/html
    ports:
      - 1234:80

  db:
    container_name: redux-db
    image: mariadb:10.6.4
    restart: always
    environment:
      - MYSQL_DATABASE=exo
      - MYSQL_ROOT_PASSWORD=azerty
      - MYSQL_USER=hetic
      - MYSQL_PASSWORD=hetic
    ports:
      - 3306:80

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 2345:80
    restart: always
    environment:
      - PMA_ARBITRARY=1
